### ISSUE TITLE
Our Stories - Make Avatar and Org Log Clickable

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1515]
When the Avatar or Logo is clicked, direct to Volunteer View page or Organization View page.

![image](https://user-images.githubusercontent.com/24813620/32417613-9f83cbd0-c221-11e7-90c0-9151c44b1092.png)

![image](https://user-images.githubusercontent.com/24813620/32417615-a62e70c0-c221-11e7-961a-d8af462587a0.png)

**Comment by SavannahFloyd** [comment]
I am currently working on resolving this issue. I have made it so that the Avatar/Logo is clickable; however, I am having trouble testing to make sure my solution goes to the correct Volunteer/Organization page since there is only dummy data in the stories. What would be the easiest way for me to test?
