### ISSUE TITLE
Settings page comes up for < 1s then disappears

### ISSUE THREAD

**Issue by andy5995** [Code4SocialGood/c4sg-web#1549]
I noticed this on when I signed up on the regular site a couple days ago, and now again on the dev site.

When signing up and signing in with Google for the first time, the settings page pops up for < 1s, disappears, then I'm presented with the main page.

I can still get to my settings ok.

**Comment by asevans48** [comment]
Please let me know when this is solved so I can have it implemented into our test plans.

**Comment by Code4SocialGood** [comment]
@asevans48 @andy5995 
This behaves as designed. We use Auth0 as identity management tool. Due to the limitation/restriction of Auth0 API, there are a couple of scenarios that is not ideal, but we have to live with it:

1. Register as social login
Setup page pops and disappear

2. Register as email login
User is logged in but immediately kicked out. User has to login again. 

We don't expect these issues to be resolved, unless we switch to another identity management tool, or, unless we get a senior developer who understand Auth0 (any change to Auth0 integration must be very cautious). 

I added label of Auth0 for this issue, keep this issue open. However, we are not expecting solutions to any Auth0 issues in the near future.
