### ISSUE TITLE
[10/31/2017][4:30pm] New User Registration Issue

### ISSUE THREAD

**Issue by asevans48** [Code4SocialGood/c4sg-web#1550]
Author: Anu
Please see the following link for more information
Link: https://github.com/anuvenkatesh1/c4sg-qa/wiki/Bug-Reports-for-C4SG

**Comment by Code4SocialGood** [comment]
User is not actually registered. 

Here is the steps on register a user with email address:
1. Enter email and password, click Sign Up
2. Login to email account and click validation link
3. Enter email and password, click Login

Step #2 is for the purpose of email validation. If user enters an invalid email address or someone else' email address, user is not able to validate from email account, and can not login. 

If user enters an invalid email address, it is not an issue. Since user can't login anyway.
If user enters someone's email address, it is not an issue. Since the user can't login anyway. It is also not an issue for the other user. If the other user want to register later, he can just click the validation link is his email. However, if the other user deleted that email, it will be an issue.

What we could do, for this defect, is to add an enhancement:
`**Provide user the option to resend validation link.**`

**- User with Invalid Email Address**
![image](https://user-images.githubusercontent.com/24813620/32639472-bbb9c014-c589-11e7-8bc8-f71455d3fa6c.png)

![image](https://user-images.githubusercontent.com/24813620/32639490-d0e25d16-c589-11e7-85d1-a8eeb94776f9.png)

**- User with Valid Email Address**
![image](https://user-images.githubusercontent.com/24813620/32639538-09cbbffa-c58a-11e7-8c4b-08d9b74d029c.png)

![image](https://user-images.githubusercontent.com/24813620/32639512-f020ff48-c589-11e7-9bb2-76390aac5c90.png)
