### ISSUE TITLE
Home Page Loading is Slow

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1674]
Study what causes the slowness, and fix it.

1 Video is 1MB, size is not too large
2. Map - User count in country is hard coded, won't cause performance concern
3. Map - Statistics: Volunteer, Organizations: do we retrieve count only from backend?

**Comment by SouravInsights** [comment]
@Code4SocialGood  Page load time is really very slow. I just used Lighthouse to check the website's performance and other related issues. 
I'm adding the screenshot of the report that I got. I'll try to find other bugs and let you know.

![capture](https://user-images.githubusercontent.com/26466468/33283844-1bec79d4-d3d3-11e7-8f26-c8b16fd928bf.JPG)

**Comment by istride** [comment]
I used the _Performance_ tab in Chrome's Developer Tools to analyse this (screenshots below). This was done, firstly, with clear cache, then with cached assets. I've also attached the profiles.

On the first load, what seems to be taking the most time is downloading JS - mostly `vendor` (5.69 s). Once downloaded, it needs to be evaluated, which takes another half a second and then the page is rendered, which takes another 300 ms. The net result is that over seven seconds pass before the home page is even displayed, in my particular case.

On the reload, download time is much reduced, as expected, due to the caching. It is still close to 1 second before `main` gets evaluated, which takes half a second, again, plus the 300 ms of rendering time.

I'm not sure what to suggest to improve this situation as I'm very new to Angular, but here are a few obvious things:

* Somehow try to reduce the size of the deployed JS
* Make sure the deployed JS assets are gzipped by the server
* Look into pre-rendering

![c4sg-home-page-first-load](https://user-images.githubusercontent.com/553684/33398633-8cf391e2-d547-11e7-9701-19df4e63f679.png)

![cs4g-home-page-reload](https://user-images.githubusercontent.com/553684/33398646-9791ecca-d547-11e7-83f1-afcc94c1d878.png)

[profiles.zip](https://github.com/Code4SocialGood/c4sg-web/files/1515515/profiles.zip)

**Comment by Code4SocialGood** [comment]
@istride Thank you for the performance analysis!

**Comment by istride** [comment]
This [gzip compression checker](https://checkgzipcompression.com/?url=https%3A%2F%2Fapp.code4socialgood.org) says that g4sg is not gzipping its assets. Does anyone know how to enable this?

**Comment by istride** [comment]
Sorry, I don't think I used that gzip checker correctly. Here's a better example with the most recent vendor bundle JS. It probably goes without saying that enabling compression would improve performance very noticeably.

![checkgzipcompression com-vendor-bundle](https://user-images.githubusercontent.com/553684/33410673-53cdf5d8-d579-11e7-8f3c-bff26c713619.png)

**Comment by istride** [comment]
Enabled compression in PR #1740

**Comment by Code4SocialGood** [comment]
Keep this issue open, to explore if there are other approaches to make the home page load faster.
