### ISSUE TITLE
Home Page - Featured Video is not displaying

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1831]
![image](https://user-images.githubusercontent.com/24813620/42456406-736af8b6-835a-11e8-9f65-4d6fbd08b92f.png)

**Comment by Outte** [comment]
There doesn't seem to be an issue with the video itself. Instead, the issue seems to be with the autoplay feature on HTML videos. I noticed this issue seems to only affect Chrome. I suspect it has something to do with Google's recent [autoplay policy changes](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes). The problem with that is Code for Social Good actually is compliant with the policy changes because our video is muted. Does anyone have any ideas on what may be causing this issue?

**Comment by Code4SocialGood** [comment]
That makes sense, since our code has not changed. It must be something external that causes the video issue.
