### ISSUE TITLE
Prod Site - Can't Login

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#1832]
Login failed with error: Invalid state
This is related to Auth0 that we use in the application. The login is actually successful, but the call back failed. 

Dev site works fine though.

**Comment by SunyataZero** [comment]
I'm having the same issue with both my user account and org account

**Comment by Code4SocialGood** [comment]
Link: https://app.code4socialgood.org/

**Comment by Code4SocialGood** [comment]
**DEV Site: http://dev.code4socialgood.org/**
Register and Login works fine. 

**PROD Site: https://app.code4socialgood.org/**
Register and Login not working.
Test Case: 
Login with: code4socialgood@gmail.com / Goodsocialcode1!
Error Message: Invalid state
Error Log: Failed to load resource: the server responded with a status of 403 ()

Identity Management: Auth0
Integration with Auth0: Please reference frontend code in this repository

![image](https://user-images.githubusercontent.com/24813620/43902486-d6328c80-9baf-11e8-8599-aecacc8fecec.png)

![image](https://user-images.githubusercontent.com/24813620/43904204-b739d21c-9bb3-11e8-9c79-c05ccb9507ae.png)

**Comment by Code4SocialGood** [comment]
Code integration in C4SG-Web repository:
Environments: https://github.com/Code4SocialGood/c4sg-web/tree/master/src/environments
Source (auth.xxx.ts): https://github.com/Code4SocialGood/c4sg-web/tree/master/src/app

**Comment by SunyataZero** [comment]
This bug was because of [**an update of auth0**](https://community.auth0.com/t/upgrade-reminder-changes-to-deprecation-roadmap/9552)

To solve this problem we changed the version of the auth0 js lib in the auth0.com custom login html:
Old:
`<script src="https://cdn.auth0.com/js/auth0/8.8/auth0.min.js"></script>`
New:
`<script src="https://cdn.auth0.com/js/auth0/9.6.0/auth0.min.js"></script>`

The custom login html can be found (and edited) in the auth0.com control panel (after logging in), under *Hosted Pages* (in the left-side menu)

This problem has been solved but here are some todos to reduce the risk for similar problems in the future:
* [ ] At least one person can subscribe to the [announcements from auth0.com](https://community.auth0.com/c/announcements)
* [ ] possibly adding documentation to explain these things
