### ISSUE TITLE
[request] page does not redirect/refresh on login, logout

### ISSUE THREAD

**Issue by russon77** [Code4SocialGood/c4sg-web#188]
## expected behavior

- when in any route other than home (i.e. `/project/list`), clicking Login should not redirect to home `/`
- logging in should not hard refresh the page
- logging out should not refresh the page

**Comment by gugui3z24** [comment]
**Fix: BranchIssue188**

**1. Issued on being redirected when clicking logout can be fixed by using this inside of the login link:**

`routerLink="#" ` instead of `routerLink=""`

**2. Issue on logging in and hard refresh cannot be fixed since Auth0 requires a redirect to a callbackURL.** 

**3. Issued on hard refresh when loging out can be fixed by: in auth.service, instead of setting the window.location manually, use router:**
```
window.location.href = logoutURL; // Instead of this
this.router.navigate(['/']); // Use this
```

**Comment by Code4SocialGood** [comment]
@parloti @gugui3z24 

Two PRs have been merged (#497 and #498) attempting to resolve the issue. Unfortunately, issue of redirect on login still exists. 
- **#497**
`<li><a class="log-reg" routerLink="#" (click)="authSvc.login()" *ngIf="!authSvc.authenticated()">Log In</a></li>`
- **#498** 
`<li><a class="log-reg" (click)="authSvc.login()" *ngIf="!authSvc.authenticated()">Log In</a></li>`

**Test cases**
User Action: Click Projects. Login (mydummytest1@gmail.com / dummypassword). 
System Response: User is redirected to home page instead of staying on Projects page.

Due to the low priority of this issue, we will move this issue to Next Release. Please feel free to work on other higher priority issues, and revisit this issue after the MVP release in July.

**Comment by parloti** [comment]
There were two problems, first was the routing that redirects to the home page, immediately after clicking the log in/log out button, this has been resolved, either without routerLink or routerLink = "#".

After authentication auth.service also redirects to home page.

```
auth: {
       redirectUrl: window.location.origin,
      ...
  }
```

Solution #356 would redirect the user back to the page that requested log in / log out, but the lines of code added were left in the wrong place.

Items 2 and 3 of #188 is partially implementable, but it is more complex.
As shown here:
https://auth0.com/docs/libraries/lock/v10/popup-mode

**Comment by Code4SocialGood** [comment]
Closed. Trivial issue. Not worth extra time.
