### ISSUE TITLE
User List Page: Empty User card being displayed in the User list

### ISSUE THREAD

**Issue by rituven** [Code4SocialGood/c4sg-web#359]
An empty user card is displayed at the top of the user list page. There is no data in the card.
![screen shot 2017-05-24 at 12 05 41 pm](https://cloud.githubusercontent.com/assets/12638803/26421023/575d0166-4079-11e7-9c4d-346835a9f42e.png)

**Comment by Code4SocialGood** [comment]
- **Why this happen**
When a user is signed up, we only ask for email address and password. Therefore this user is shown as a empty card. 

- **How to fix**
1. In user edit page, make the following fields mandatory:
Username, Email Address, First Name, Last Name, Country

- **Explanation**
1. When user sign up, email address and password is filled. The default value of publish_flag is 'N', which means don't make this user profile public on the web page. This user won't shown in Volunteer List. (note, currently you see all users on the volunteer list even if their public_flag is 'N', this is incorrect, it will be fixed in #361 )
2. When user logon  and edit their user setting, they can change their publish_flag to Y. And in order to save the change, they must fill in all the mandatory fields. So if public_flag is 'Y', the first name and last name must have value. The user card on volunteer list will never be empty.
