### ISSUE TITLE
Organization link doesn't work on Project page - Issue in IE 

### ISSUE THREAD

**Issue by p-tal** [Code4SocialGood/c4sg-web#603]
Step to reproduce:
1. Click on organizations from home page.
2. Select an organization from right hand side.
3. Click on open project.
4. Click on "Organization" link on right hand side on Project page.

Issue:
Nothing happens.
Expected Result:
User should be taken back to "organization" Page.

![project apply](https://user-images.githubusercontent.com/29553195/27651326-ec1b6124-5c05-11e7-8303-dafaf25f90a9.jpg)

**Comment by Code4SocialGood** [comment]
I am not able to recreate this issue. Here is what I get on that page. Please note that the URL is the same.
I suspect you see the issue because of the sequence of browse actions you took. Could you describe how to recreate this problem?

![image](https://user-images.githubusercontent.com/24813620/27652410-39500256-5c01-11e7-8850-d5fd08a1c081.png)

**Comment by p-tal** [comment]
Hi , I have followed the steps below, Also I am trying this steps without Login In.
URL: http://dev.code4socialgood.org/project/view/122
Step to reproduce:
Click on organizations from home page.
Select an organization from right hand side.
Click on open project.
Click on "Organization" link on right hand side on Project page

**Comment by Code4SocialGood** [comment]
This problem could be recreated in IE. It works fine in Chrome.

**Comment by Code4SocialGood** [comment]
Resolved in PR#1032
