### ISSUE TITLE
Change Request: Please disable EDIT/DELETE options from ADMIN's "Approve Organization" queue

### ISSUE THREAD

**Issue by p-tal** [Code4SocialGood/c4sg-web#845]
Change Request to disable EDIT/DELETE option from admin user in "approve organization" queue. Admin can update changes if required from database

**Comment by Code4SocialGood** [comment]
After second thought, let's keep the buttons enabled there. So that if user report application issues, we could login as admin user and recreate the problem. Otherwise, we are not able to perform such prod support if we only have test account.

Since there will be very limited people (maybe just one) to be admin user initially, those buttons won't be overused. They will not be clicked unless absolutely.

Please close this issue, it is work as designed, not a defect.

**Comment by p-tal** [comment]
As designed. Defect ok to close.
