### ISSUE TITLE
Organization user unable to save Edited Project|| Env Stage

### ISSUE THREAD

**Issue by p-tal** [Code4SocialGood/c4sg-web#891]
1. Login as a organization user
2. Go to create project and save it.
3. Goto same project and try to edit the same.

Actual Result:
User not able to save it as SAVE button is not enabled

**Comment by Code4SocialGood** [comment]
Which organization does this user belongs to? 

As  you see from the data below, only one organization is active (A) and able to post projects. 
The other organizations (either in N or D) should not be able to create projects. There are projects for those org with status N (not being approve yet) because the projects are created before we add more rules. 

Could you test this issue on an Active organization to see if it is an issue? If it works fine for active org, then this issue is bad data issue, I will clean up the staging database. 

![image](https://user-images.githubusercontent.com/24813620/28597933-3bf1a670-7166-11e7-9f86-20dbf937119a.png)

**Comment by p-tal** [comment]
User is able to edit and save project. Defect OK to close
