### ISSUE TITLE
Run "npm start" will show tslint warnings

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-web#98]

**Comment by russon77** [comment]
i don't know if it exactly makes sense for this to display with `npm start`. i think there's tools to add a comment/review to a PR based on tslint output actually. let me look into those first.

**Comment by Code4SocialGood** [comment]
As a developer, I validate my code by:
1. run npm start: there is no warning or error
2. launch browser: web page works as expected.

The only opportunity to **_"force"_** me see the tslint warning is through npm start.
There might be other commands I can run to check with tslint, but as a lazy developer... I might omit it.

Then it comes to another topic: how important is tslint? Do we want to enforce it, or, only make it nice to have?

**Comment by russon77** [comment]
honestly i don't think that the linter is incredibly important. it's mostly style errors, like spacing/tabs, whitespace, using 'const' instead of 'let', some other styling errors.. i don't see it working exactly with `npm start`, especially with so many errors already.

maybe we could create another task to 1) confirm the tslint configuration project-wide (get a group consensus) and 2) fix all current errors before forcing its use by adding to travis? running `npm run lint` will return non-zero if there are errors, so travis would "fail".
